import { CacheService } from '../types';
import { logger } from './logger';
import {
    fetchPlayerResponse,
    extractCaptionTracks,
    selectCaptionTrack,
    fetchCaptionContent,
    decodeEntities,
} from './youtube-page';

/**
 * YouTube transcript extraction service.
 *
 * Fetches the watch page via Obsidian's CORS-free `requestUrl`, parses the
 * embedded `ytInitialPlayerResponse`, selects a caption track (honoring a
 * preferred language), then downloads and parses the timedtext payload.
 */

export interface TranscriptSegment {
    text: string;
    start: number;
    duration: number;
}

export interface Transcript {
    segments: TranscriptSegment[];
    fullText: string;
    language: string;
    autoGenerated: boolean;
}

export class YouTubeTranscriptService {
    private readonly transcriptTTL = 1000 * 60 * 60 * 24 * 7; // 7 days

    constructor(private cache?: CacheService) {}

    /**
     * Extract a transcript for a YouTube video.
     * @param videoId 11-character video id
     * @param language Optional preferred language code (e.g. "en", "es"). Falls
     *                 back to English, then the first available track.
     */
    async getTranscript(videoId: string, language?: string): Promise<Transcript | null> {
        if (!videoId) {
            throw new Error('Video ID is required');
        }

        const cacheKey = language ? `transcript-${videoId}-${language}` : `transcript-${videoId}`;

        const cached = this.cache?.get<Transcript>(cacheKey);
        if (cached) {
            return cached;
        }

        const transcript = await this.fetchTranscript(videoId, language);

        if (transcript) {
            this.cache?.set(cacheKey, transcript, this.transcriptTTL);
        }

        return transcript;
    }

    /**
     * Fetch transcript by parsing the watch page's caption tracks.
     */
    private async fetchTranscript(videoId: string, language?: string): Promise<Transcript | null> {
        try {
            const playerResponse = await fetchPlayerResponse(videoId);
            if (!playerResponse) {
                logger.warn('Transcript: could not parse player response', 'Transcript', { videoId });
                return null;
            }

            const tracks = extractCaptionTracks(playerResponse);
            if (tracks.length === 0) {
                logger.info('Transcript: no caption tracks available', 'Transcript', { videoId });
                return null;
            }

            const track = selectCaptionTrack(tracks, language);
            if (!track?.baseUrl) {
                logger.warn('Transcript: no suitable caption track found', 'Transcript', {
                    videoId,
                    languages: tracks.map(t => t.languageCode),
                });
                return null;
            }

            const xml = await fetchCaptionContent(track.baseUrl);
            const transcript = this.parseXMLTranscript(xml, track.languageCode || 'en', track.kind === 'asr');

            if (transcript.segments.length === 0) {
                logger.warn('Transcript: caption payload parsed but was empty', 'Transcript', { videoId });
                return null;
            }

            logger.info('Transcript fetched', 'Transcript', {
                videoId,
                language: transcript.language,
                segments: transcript.segments.length,
                length: transcript.fullText.length,
            });
            return transcript;
        } catch (error) {
            logger.warn('Transcript: fetch failed', 'Transcript', {
                videoId,
                error: error instanceof Error ? error.message : String(error),
            });
            return null;
        }
    }

    /**
     * Parse a timedtext XML payload into segments.
     * Handles both the default `<text start="" dur="">` shape and the
     * srv3 `<t s="" d="">` shape so we are robust to YouTube's format variance.
     */
    private parseXMLTranscript(xmlText: string, language: string, autoGenerated: boolean): Transcript {
        const parser = new DOMParser();
        const xmlDoc = parser.parseFromString(xmlText, 'text/xml');

        const textElements = xmlDoc.getElementsByTagName('text');
        const elements = textElements.length > 0 ? textElements : xmlDoc.getElementsByTagName('t');

        const segments: TranscriptSegment[] = [];
        let fullText = '';

        for (let i = 0; i < elements.length; i++) {
            const element = elements[i];
            if (!element) continue;
            const raw = element.textContent ?? '';
            const text = decodeEntities(raw).replace(/\s+/g, ' ').trim();
            const start = parseFloat(element.getAttribute('start') ?? element.getAttribute('s') ?? '0');
            const duration = parseFloat(element.getAttribute('dur') ?? element.getAttribute('d') ?? '0');

            if (text) {
                segments.push({ text, start, duration });
                fullText += `${text} `;
            }
        }

        return {
            segments,
            fullText: fullText.trim(),
            language,
            autoGenerated,
        };
    }

    /**
     * Check if a transcript is available for a video.
     */
    async isTranscriptAvailable(videoId: string): Promise<boolean> {
        const transcript = await this.getTranscript(videoId);
        return transcript !== null && transcript.segments.length > 0;
    }
}
