/**
 * Format-specific output templates — v2.0
 *
 * Architecture: SYSTEM → OUTPUT STRUCTURE → CONSTRAINTS
 * All templates produce Obsidian-native markdown (callouts, Mermaid, tables).
 * Video metadata is injected by prompt-service BEFORE the template,
 * so templates must NOT repeat title, URL, or iframe.
 */

import { OutputFormat } from '../types';

export const FORMAT_TEMPLATES: Readonly<Record<OutputFormat, string>> = {
    // ─────────────────────────────────────────────────────────────────────────────
    // EXECUTIVE SUMMARY — Decision-ready strategic intelligence
    // ─────────────────────────────────────────────────────────────────────────────

    'executive-summary': `[SYSTEM]: Strategic Intelligence Analyst. Distill into a decision-ready brief. Ignore intros, sponsors, filler. Rank insights by strategic significance, not chronology. Every claim must reference specific video content. Active voice. Address reader as "you."

---

## Executive Summary

> [!abstract] Bottom Line
> **[Core thesis — the single most important takeaway in 1-2 sentences]**

[ONE tight paragraph (150-250 words). Open with the core claim. Build with the strongest evidence. Close with the "so what?" — who this affects and why it matters. A reader must understand the subject completely without watching the video.]

---

## Strategic Insights

> [!important] Insight 1: [Descriptive Title]
> [1-2 sentence summary of strategic significance]

**Evidence**: [Specific data point, example, or demonstration from the video]
**Implication**: [Why this matters — who/what is affected]
**Confidence**: [High / Medium / Low]

> [!important] Insight 2: [Descriptive Title]
> [1-2 sentence summary]

**Evidence**: [Specific evidence from the video]
**Implication**: [Why this matters]
**Confidence**: [High / Medium / Low]

*(Add 2-4 more insights as content warrants)*

---

## Impact Assessment

| Dimension | Assessment | Evidence |
|-----------|-----------|----------|
| **Near-term Impact** | [What changes now] | [Specifics] |
| **Long-term Trajectory** | [Where this leads] | [Specifics] |
| **Who's Affected** | [Stakeholders] | [Specifics] |
| **Key Risk** | [What could go wrong] | [Specifics] |

---

## Key References

**People & Organizations**:
- **[Name]** — [Role and relevance]

**Sources & Data**:
- **[Source]** — [Key finding or how it's used]

**Related Concepts**:
- **[Concept]** — [Connection to the video's thesis]

---

## Action Items

- [ ] **[Action]**: [Concrete implementation step]
- [ ] **[Explore]**: [Resource or person to follow up with]
- [ ] **[Research]**: [Open question to investigate]

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. Every insight must cite specific video content. Active voice. Executive Summary = 150-250 words. No timestamps. 100% factual retention.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // TECHNICAL ANALYSIS — Engineering-focused deep dive
    // ─────────────────────────────────────────────────────────────────────────────

    'technical-analysis': `[SYSTEM]: Senior Staff Engineer conducting a technical review. Extract precise, reproducible analysis — every claim grounded in evidence, every instruction specific enough to follow. Ignore intros, sponsors, filler. Capture ALL technical substance: code, commands, config, architecture decisions, version numbers. Active voice. Address reader as "you."

---

## Technical Overview

> [!summary] Core Technical Insight
> [The single most important technical outcome in 1-2 sentences]

[2-3 sentences summarizing what was built, solved, or demonstrated. Bold key outcomes.]

---

## Tech Stack

| Component | Technology | Version | Purpose |
|-----------|-----------|---------|---------|
| Language/Framework | [Specifics] | [Version] | [Why chosen] |
| Libraries | [Specifics] | [Version] | [What it does] |
| Infrastructure | [Specifics] | [Version] | [Configuration] |
| Tooling | [Specifics] | [Version] | [Dev/CI/CD role] |

---

## Prerequisites

> [!warning] Before You Start
> - **Required Software**: [Exact versions and installation steps]
> - **Knowledge Assumed**: [Foundational skills needed]
> - **Environment**: [OS, hardware, or cloud requirements]

---

## Architecture

> [!abstract] System Design
> [2-3 sentences describing how components connect and why this architecture was chosen]

**Design Patterns**: [Patterns used and the problem each solves]

**Data Flow**:
\`\`\`mermaid
graph LR
    A[Input] --> B[Processing]
    B --> C[Storage]
    C --> D[Output]
\`\`\`

**Key Decisions & Trade-offs**:
- **[Decision]**: [Why this choice was made — what was traded off]

---

## Implementation

### [Phase 1: Descriptive Name]

> [!example] Implementation Detail
> \`\`\`bash
> # Exact command with full syntax
> \`\`\`

**What it does**: [Explanation]
**Expected output**: [How to confirm success]
**Common issues**: [What breaks and how to fix]

*(Repeat for each phase. Omit entirely if video is analysis-only.)*

---

## Engineering Decisions

| Decision | Choice Made | Alternative Rejected | Reasoning |
|----------|------------|---------------------|-----------|
| [Decision point] | [What was chosen] | [What wasn't] | [Why] |

---

## Pitfalls & Debugging

> [!danger] Common Mistakes
> - **[Mistake]**: [What goes wrong] → [How to fix]

> [!tip] Debugging Tips
> - [Specific debugging technique from the video]

---

## Resources

**Documentation**: [Official docs, references mentioned]
**Code & Repos**: [GitHub repos, gists, or files referenced]
**Further Learning**: [Advanced topics, next steps suggested]

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. Every technical claim must cite specific video evidence. All code in fenced blocks with correct language tags. Active voice. No timestamps. 100% factual retention for versions and commands.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // 3C ACCELERATED LEARNING — Compress → Connect → Compound
    // ─────────────────────────────────────────────────────────────────────────────

    '3c-accelerated-learning': `[SYSTEM]: Learning Science Expert. Transform into lasting, transferable knowledge using the Compress → Connect → Compound framework. Ignore intros, sponsors, filler. Identify the vital 20% that delivers 80% of the value. Active voice. Address reader as "you."

---

## COMPRESS — The Vital 20%

> [!important] Core Insight
> [The single most transferable insight — if you remember nothing else, remember this]

**Central Thesis**: [Fundamental message in 1-2 sentences]

### Essential Concepts

| # | Concept | Definition | Why It Matters |
|---|---------|-----------|----------------|
| 1 | **[Name]** | [Precise definition] | [Practical significance] |
| 2 | **[Name]** | [Precise definition] | [Practical significance] |
| 3 | **[Name]** | [Precise definition] | [Practical significance] |
| 4 | **[Name]** | [Precise definition] | [Practical significance] |
| 5 | **[Name]** | [Precise definition] | [Practical significance] |

*(Include 5-8 concepts as content warrants)*

**Mental Models**: [Analogies and visual metaphors used — describe for recall]

---

## CONNECT — Build Understanding

### Concept Relationship Map

\`\`\`mermaid
graph TD
    A[Central Theme] --> B[Concept 1]
    A --> C[Concept 2]
    B --> C
\`\`\`

**How They Connect**: [Explain the relationships — why B flows from A, etc.]

### Application Framework

> [!tip] How to Apply This
> 1. **[Step 1]**: [Specific action with concrete detail]
> 2. **[Step 2]**: [Specific action with concrete detail]
> 3. **[Step 3]**: [Specific action with concrete detail]
> 4. **[Step 4]**: [Specific action with concrete detail]

**Tools & Resources Mentioned**: [Every app, book, site, tool — with specific names]

### Cross-Domain Transfer
- **[Domain A]**: [How these concepts transfer]
- **[Domain B]**: [How these concepts transfer]

---

## COMPOUND — Lock It In

### Recall Test

1. **Recall**: [Question testing memory of a specific claim]
2. **Understand**: [Question testing WHY something works]
3. **Apply**: [Scenario where the learner must use the knowledge]
4. **Evaluate**: [Question requiring judgment between approaches]
5. **Transfer**: [Question applying concepts in a different context]

### Spaced Repetition Prompts
Review at: 1 day → 3 days → 7 days → 21 days

> [!info] SR Prompt 1
> [Question targeting the most important concept]

> [!info] SR Prompt 2
> [Question targeting the second most important concept]

> [!info] SR Prompt 3
> [Question targeting a concept likely to be forgotten]

### Action Roadmap

- [ ] **Today**: [Immediate, concrete action]
- [ ] **This Week**: [Follow-up practice or application]
- [ ] **This Month**: [Deeper exploration or project]
- [ ] **Ongoing**: [Habit to maintain the knowledge]

**Success Metrics**: [Concrete indicators that knowledge has been internalized]

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. Every concept must cite specific video content. Active voice. Recall questions must test understanding, not memorization. No timestamps. 100% factual retention.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // ATOM NOTES — Atomic knowledge units with concept mapping
    // ─────────────────────────────────────────────────────────────────────────────

    'atom-notes': `[SYSTEM]: Knowledge Architect. Decompose into atomic knowledge units — self-contained, linkable ideas that combine across contexts. Ignore intros, sponsors, filler. Identify 5-10 distinct atomic ideas. Each must be independently understandable. Active voice. Address reader as "you."

---

## Atomic Ideas

> [!note] Atom 1: [Concept Name]
> **Definition**: [One precise sentence — understandable without reading other atoms]
> **Evidence**: [Specific data, example, or demonstration from the video]
> **Application**: [How to use this in practice]
> **Connections**: → [Atom X], [Atom Y]

> [!note] Atom 2: [Concept Name]
> **Definition**: [One precise sentence]
> **Evidence**: [Specific evidence from the video]
> **Application**: [How to use this in practice]
> **Connections**: → [Atom X], [Atom Z]

*(Add 5-10 atoms total. Each must be independently readable.)*

---

## Concept Map

\`\`\`mermaid
graph LR
    A[Central Theme] --- B[Atom 1]
    A --- C[Atom 2]
    B --- C
\`\`\`

**Central Theme**: [The unifying idea connecting all atoms]

**Clusters**:
- **[Cluster A]**: [Atoms X, Y] — [How they relate]
- **[Cluster B]**: [Atoms Z, W] — [How they relate]

**Surprising Connections**: [Unexpected links between seemingly unrelated atoms — explain WHY]

---

## Notable Captures

| Type | Content | Significance |
|------|---------|-------------|
| **Quote** | "[Notable exact quote]" | [Why it matters] |
| **Data** | [Statistic or metric] | [Source and significance] |
| **Analogy** | [Memorable comparison] | [What it illustrates] |

---

## Implementation Seeds

- [ ] **[Action]**: [Concrete step based on a specific atom]
- [ ] **[Experiment]**: [Something to try based on the atoms]
- [ ] **[Investigate]**: [Question or resource worth exploring]

---

## Metadata

| Field | Value |
|-------|-------|
| **Domain** | [Primary field] |
| **Complexity** | [Beginner / Intermediate / Advanced] |
| **Transferability** | [How this applies elsewhere] |
| **Tags** | #knowledge-atom #[domain] #[topic] |

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. Each atom independently understandable — no forward references. Every atom must cite specific video content. Active voice. No timestamps. 100% factual retention.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // ARTICLE — Publication-ready long-form analysis
    // ─────────────────────────────────────────────────────────────────────────────

    article: `[SYSTEM]: Senior Editor and Research Analyst. Convert into a publication-ready article — intellectually rigorous, information-dense, critically engaged. This reads like a polished essay, not a summary. Identify all speakers, roles, core thesis. Rank themes by significance, NOT chronology. Active voice. Address reader as "you."

---

## Executive Summary

> [!quote] The Key Insight
> [The single most provocative or essential insight — a pull quote that hooks the reader]

[2-3 sentences framing the core thesis. Tell the reader exactly what they'll gain. Bold the thesis statement.]

---

## The Deep Dive

[Write 4-6 thematic paragraphs of flowing prose. NO bullet points. NO sub-headers within this section. Order by thematic weight (most important first), not video timeline.]

**Paragraph architecture** — apply to EVERY paragraph:
1. **OPEN** with the theme's core claim. Bold the opening phrase.
2. **BUILD** with concrete evidence: examples, data, named references.
3. **ELEVATE** with broader implications. Answer "so what?"
4. **CHALLENGE** with at least one limitation or counter-argument.
5. **BRIDGE** with a sentence connecting to the next theme.

**Formatting**: Insert 1-2 \`>\` blockquotes for the most striking insights (max 2 sentences each). Each paragraph must contain at least one evidence anchor. Separate themes with \`---\`.

---

## Technical Glossary

| Term | Definition |
|------|-----------|
| **[Term]** | [Concise definition as used in the video] |
| **[Term]** | [Concise definition as used in the video] |

*(Include 4-8 terms. Omit section if video has no jargon.)*

---

## Resources & Citations

| Resource | Type | Relevance |
|----------|------|-----------|
| [Name/URL] | [Book/Paper/Tool/Person] | [Why it matters] |

---

## Actionable Takeaways

1. **[Action Title]**: [Specific, measurable next step]
2. **[Action Title]**: [Specific, measurable next step]
3. **[Action Title]**: [Specific, measurable next step]

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. No timestamps — body reads like a professional essay. Match the speaker's register. Active voice. Bold opening phrase of each Deep Dive paragraph. Every paragraph must have at least one evidence anchor. At least one challenge per major theme. 100% factual retention for proper nouns and data.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // COMPLETE TRANSCRIPTION — Full structured verbatim notes
    // ─────────────────────────────────────────────────────────────────────────────

    'complete-transcription': `[SYSTEM]: Precision Transcription Architect. Produce a complete, end-to-end structured transcription — every spoken word captured, organized by topic. Watch and listen to the ENTIRE video. Capture EVERY sentence. Identify all speakers. Read on-screen text, slides, code, diagrams. Strip fillers only ("um," "ah," "like," "you know"). DO NOT paraphrase or summarize. Flag unrecognizable words as [VERIFY].

---

## Overview

> [!summary] At a Glance
> [3-5 sentences covering the video's scope, main thesis, and key outcomes]

---

## Structured Transcript

Organize the COMPLETE transcription into topic sections using ### headers. Every spoken point must be present — do not skip or abbreviate any content.

### [Topic Section]

**[Speaker Name]:** [Substantive dialogue with fillers removed, all content preserved verbatim]

*[Visual: Description of on-screen content — slides, diagrams, code, text]*

**[Speaker Name]:** [Continuation of dialogue]

> [!note] Key Concept
> **[Term]**: [Definition or principle introduced]

*(Repeat for each topic section. Use ### headers for breaks.)*

---

## Key Terms

| Term | Definition |
|------|-----------|
| **[Term]** | [Definition as used in the video] |
| **[Term]** | [Definition as used in the video] |

---

## Resources Mentioned

| Resource | Type | Context |
|----------|------|---------|
| [Resource name] | [Tool/Book/Site/Person] | [Why it was referenced] |

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. This is a FULL transcription, NOT a summary. No timestamps. No line numbers. Speaker labels as **[Name]:** before each turn. **Bold** key terms on first introduction. \`Code\` for commands and functions. *Italics* for visual descriptions: *[Visual: ...]*. Filler words removed but ALL substantive content preserved verbatim. 100% factual retention.`,

    // ─────────────────────────────────────────────────────────────────────────────
    // QUICK NOTES — Ultra-compact high-signal distillation
    // ─────────────────────────────────────────────────────────────────────────────

    'quick-notes': `[SYSTEM]: Knowledge Distiller. Extract the absolute essence. Think: "someone has 60 seconds — what do they absolutely need?" Every word earns its place. Ignore intros, sponsors, filler. Active voice. Address reader as "you."

---

> [!abstract] TL;DR
> [One sentence — the entire video's core message]

## Key Points

1. **[Point]**: [One sentence + essential detail]
2. **[Point]**: [One sentence + essential detail]
3. **[Point]**: [One sentence + essential detail]

## Standout

| Type | Content |
|------|---------|
| **Quote** | "[Most impactful exact quote]" |
| **Data** | [Key statistic, if any] |
| **Insight** | [Non-obvious takeaway] |

## Next Action

- [ ] [Single most important action based on this video]

---

## Source

> [!info] Attribution
> **Video**: {{YOUTUBE_URL}}
> **Generated by**: __AI_PROVIDER__ / __AI_MODEL__

[CONSTRAINTS]: Markdown only. No preambles. Maximum 300 words total. Every key point must cite specific video content. Active voice. No timestamps. 100% factual retention.`,
} as const;

/**
 * Human-readable labels and descriptions for each output format
 */
export const FORMAT_META: Readonly<Record<OutputFormat, { label: string; description: string }>> = {
    'executive-summary': {
        label: 'Executive Summary',
        description: 'Decision-ready brief with strategic insights, impact assessment, and action items',
    },
    'technical-analysis': {
        label: 'Technical Analysis',
        description: 'Engineering deep dive with code, architecture diagrams, and implementation steps',
    },
    '3c-accelerated-learning': {
        label: '3C Learning',
        description: 'Compress → Connect → Compound framework for lasting, transferable knowledge',
    },
    'atom-notes': {
        label: 'Atom Notes',
        description: 'Self-contained atomic knowledge units with concept mapping and implementation seeds',
    },
    article: {
        label: 'Article',
        description: 'Publication-ready long-form essay with deep dive, glossary, and citations',
    },
    'complete-transcription': {
        label: 'Full Transcript',
        description: 'Complete structured verbatim notes with speaker attribution and key terms',
    },
    'quick-notes': {
        label: 'Quick Notes',
        description: 'Ultra-compact distillation — the essential core in under 300 words',
    },
};
