import { TFile } from 'obsidian';

/**
 * Core interfaces and types for the YouTube Clipper plugin
 */

/** Main plugin settings */
export interface YouTubePluginSettings {
    geminiApiKey: string;
    groqApiKey: string;
    ollamaApiKey: string;
    ollamaEndpoint: string;
    huggingFaceApiKey: string;
    openRouterApiKey: string;
    outputPath: string;
    useEnvironmentVariables: boolean;
    environmentPrefix: string;
    modelOptionsCache?: Record<string, string[]>;
    modelCacheTimestamps?: Record<string, number>; // Cache timestamps for each provider
    performanceMode: PerformanceMode;
    enableParallelProcessing: boolean;
    enableAutoFallback: boolean;
    preferMultimodal: boolean;
    /** Preferred transcript language code (e.g. "en", "es"). Blank = auto (English fallback). */
    transcriptLanguage?: string;
    /** Per-format user prompt overrides. Key = OutputFormat. Empty/absent = built-in template. */
    customPrompts?: Partial<Record<OutputFormat, string>>;
    /** Emit [MM:SS](url&t=seconds) timestamp links in generated notes. */
    includeTimestamps?: boolean;
    /** Warn when a video was already processed instead of silently creating a duplicate note. */
    warnOnDuplicates?: boolean;
    /** Persist transcripts to disk so Obsidian reloads don't re-fetch YouTube. */
    persistTranscriptCache?: boolean;
    defaultMaxTokens: number;
    defaultTemperature: number;
}

/** Performance mode options */
export type PerformanceMode = 'fast' | 'balanced' | 'quality';

/** Output formats for video analysis */
export type OutputFormat =
    | 'executive-summary'
    | 'technical-analysis'
    | '3c-accelerated-learning'
    | 'atom-notes'
    | 'article'
    | 'complete-transcription'
    | 'quick-notes';

/** Video metadata from YouTube */
export interface VideoData {
    title: string;
    description: string;
    duration?: number;
    thumbnail?: string;
    channelName?: string;
    publishedAt?: string;
}

/** Response from AI provider */
export interface AIResponse {
    content: string;
    provider: string;
    model: string;
}

/** Result of video processing */
export interface ProcessingResult {
    success: boolean;
    filePath?: string;
    error?: string;
    /** Provider that actually produced the note (fallback chain may differ from selection). */
    providerUsed?: string;
    /** Model that actually produced the note. */
    modelUsed?: string;
    /** Providers that failed before the successful one, in try order. */
    failedProviders?: string[];
    /** True when the transcript exceeded the prompt budget and was truncated. */
    transcriptTruncated?: boolean;
    /** Non-fatal warnings to surface in the completion UI. */
    warnings?: string[];
    /** Set when a duplicate note already existed for this video. */
    duplicateOfPath?: string;
}

/** Options for a single processYouTubeVideo run. */
export interface ProcessingOptions {
    format?: OutputFormat;
    model?: string;
    userInstructions?: string;
    /** Called as the pipeline moves between stages, for honest progress display. */
    onProgress?: (update: ProgressUpdate) => void;
    /** Aborted when the modal closes or the plugin unloads mid-run. */
    signal?: AbortSignal;
}

/** Result of one URL inside a batch run. */
export interface BatchItemResult {
    url: string;
    result: ProcessingResult;
}

/** Pipeline stages, in execution order. */
export type ProcessStage = 'metadata' | 'transcript' | 'prompt' | 'ai' | 'save';

/** Stage progress reported by the pipeline. */
export interface ProgressUpdate {
    stage: ProcessStage;
    /** Human-readable detail, e.g. the provider currently being tried. */
    detail?: string;
    /** 0-100, only when the stage length is actually knowable. */
    percent?: number;
}

/** Per-request options threaded through the AI layer. */
export interface AIRequestOptions {
    /** Aborts in-flight fetches (modal close, plugin unload). */
    signal?: AbortSignal;
}

/** A timed transcript segment. Times are seconds since video start. */
export interface TranscriptSegment {
    start: number;
    duration: number;
    text: string;
}

/** A successfully fetched transcript. */
export interface TranscriptResult {
    fullText: string;
    segments: TranscriptSegment[];
    /** Language code of the track actually used, when known. */
    language?: string;
    /** True when the track was auto-generated (ASR) rather than manually authored. */
    isAutoGenerated?: boolean;
    /** True when fullText was truncated to fit the prompt budget. */
    truncated?: boolean;
}

/** Why a transcript could not be fetched. */
export type TranscriptFailureReason =
    | 'restricted' // age- or region-restricted
    | 'private'
    | 'unavailable' // removed / never existed
    | 'no-captions'
    | 'network'
    | 'unknown';

/** Outcome of a transcript fetch: success or a typed failure. */
export type TranscriptOutcome =
    | { ok: true; transcript: TranscriptResult }
    | { ok: false; reason: TranscriptFailureReason; message?: string };

/** AI provider interface */
export interface AIProvider {
    readonly name: string;
    model: string;
    process(prompt: string, options?: AIRequestOptions): Promise<string>;
    processWithImage?(prompt: string, images?: (string | ArrayBuffer)[], options?: AIRequestOptions): Promise<string>;
    /** Live-fetch the models available under this provider's credentials. */
    listModels?(): Promise<string[]>;
    setModel?(model: string): void;
    setTimeout?(timeout: number): void;
    setMaxTokens?(maxTokens: number): void;
    setTemperature?(temperature: number): void;
    maxTokens?: number;
    temperature?: number;
    cleanup?(): void;
}

/** Video data service interface */
export interface VideoDataService {
    extractVideoId(url: string): string | null;
    getVideoData(videoId: string): Promise<VideoData>;
    getTranscript?(videoId: string, language?: string): Promise<{ fullText: string } | null>;
    /**
     * Typed transcript fetch: success carries segments + language, failure carries
     * a machine-readable reason so the UI can explain restricted/private/no-captions.
     */
    fetchTranscriptOutcome?(videoId: string, language?: string): Promise<TranscriptOutcome>;
    getPerformanceMetrics?(): Record<string, unknown>;
    cleanup?(): void;
}

/** File service interface */
export interface FileService {
    saveToFile(title: string, content: string, outputPath: string): Promise<string>;
    openFileWithConfirmation(file: TFile): Promise<void>;
}

/** Cache metrics */
export interface CacheMetrics {
    hits: number;
    misses: number;
    evictions: number;
    size: number;
    hitRate: number;
}

/** Cache service interface */
export interface CacheService {
    get<T>(key: string): T | null;
    set<T>(key: string, value: T, ttl?: number): void;
    delete(key: string): boolean;
    clear(): void;
    getMetrics?(): CacheMetrics;
    cleanup?(): void;
    destroy?(): void;
}

/** Prompt service interface */
export interface PromptService {
    createAnalysisPrompt(options: {
        videoData: VideoData;
        videoUrl: string;
        format?: OutputFormat;
        transcript?: string;
        /** Timed segments enabling [MM:SS](url&t=seconds) timestamp links. */
        segments?: TranscriptSegment[];
        performanceMode?: PerformanceMode;
        providerName?: string;
        userInstructions?: string;
    }): string;
    processAIResponse(
        content: string,
        provider: string,
        model: string,
        format?: OutputFormat,
        videoData?: VideoData,
        videoUrl?: string,
    ): string;
}

/** Style object for CSS */
export type StyleObject = Record<string, string | number>;

/** DOM utilities interface */
export interface DOMUtilsInterface {
    applyStyles(element: HTMLElement, styles: StyleObject): void;
    createButtonContainer(parent: HTMLElement): HTMLDivElement;
    createStyledButton(
        container: HTMLElement,
        text: string,
        isPrimary?: boolean,
        onClick?: () => void,
    ): HTMLButtonElement;
}

/** Error handler interface */
export interface ErrorHandlerInterface {
    handle(error: Error, context: string, showNotice?: boolean): void;
    withErrorHandling<T>(operation: () => Promise<T>, context: string): Promise<T | null>;
}

/** Service container interface */
export interface ServiceContainer {
    aiService: AIService;
    videoService: VideoDataService;
    fileService: FileService;
    cacheService: CacheService;
    promptService: PromptService;
}

/** AI service interface */
export interface AIService {
    process(prompt: string, images?: (string | ArrayBuffer)[]): Promise<AIResponse>;
    processWith(
        providerName: string,
        prompt: string,
        overrideModel?: string,
        images?: (string | ArrayBuffer)[],
        enableFallback?: boolean,
        options?: AIRequestOptions,
    ): Promise<AIResponse>;
    /** Apply maxTokens / temperature to every provider for the next request. */
    setModelParameters?(params: { maxTokens?: number; temperature?: number }): void;
    getProviderNames(): string[];
    getProviderModels(providerName: string): string[];
    fetchLatestModels(): Promise<Record<string, string[]>>;
    fetchLatestModelsForProvider(providerName: string, bypassCache?: boolean): Promise<string[]>;
    getPerformanceMetrics?(): Record<string, unknown>;
    cleanup?(): void;
}

/** Modal event callbacks */
export interface ModalEvents {
    onConfirm: () => void | Promise<void>;
    onCancel: () => void;
}
