/**
 * Unit tests for the typed transcript outcome path: failure-reason mapping,
 * the innertube age-restriction fallback (via a mocked youtube-page fetch), the
 * character-ceiling truncation flag, and the opt-in disk cache.
 */

import { describe, it, expect, jest, beforeEach } from '@jest/globals';
import type { App } from 'obsidian';
import { YouTubeTranscriptService } from '../../../src/services/transcript-service';
import { TranscriptDiskCache, TRANSCRIPT_CACHE_MAX_FILES } from '../../../src/services/transcript-cache';
import * as youtubePage from '../../../src/services/youtube-page';
import type { TranscriptOutcome } from '../../../src/types';

jest.mock('../../../src/services/youtube-page', () => ({
    // Keep the real caption-track selection/extraction logic under test.
    ...jest.requireActual<typeof youtubePage>('../../../src/services/youtube-page'),
    fetchPlayerResponse: jest.fn(),
    fetchCaptionContent: jest.fn(),
    fetchInnertubePlayerResponse: jest.fn(),
}));
jest.mock('../../../src/services/logger', () => ({
    logger: { debug: jest.fn(), info: jest.fn(), warn: jest.fn(), error: jest.fn() },
}));

const fetchPlayerResponse = jest.mocked(youtubePage.fetchPlayerResponse);
const fetchCaptionContent = jest.mocked(youtubePage.fetchCaptionContent);
const fetchInnertubePlayerResponse = jest.mocked(youtubePage.fetchInnertubePlayerResponse);

const VIDEO_ID = 'dQw4w9WgXcQ';

/** A minimal playability payload as embedded in a watch page. */
function playability(status: string, reason: string, errorScreen?: Record<string, unknown>) {
    return { playabilityStatus: { status, reason, ...(errorScreen ? { errorScreen } : {}) } };
}

function captionsResponse(baseUrl = 'https://caption/en') {
    return {
        playabilityStatus: { status: 'OK' },
        captions: {
            playerCaptionsTracklistRenderer: {
                captionTracks: [{ baseUrl, languageCode: 'en', kind: 'asr' }],
            },
        },
    };
}

const CAPTION_XML = '<transcript><text start="0.5" dur="1.5">age gated words</text></transcript>';

describe('YouTubeTranscriptService.fetchTranscriptOutcome', () => {
    let service: YouTubeTranscriptService;

    beforeEach(() => {
        // reset (not clear) so mockResolvedValue set in one test cannot leak into the next.
        jest.resetAllMocks();
        service = new YouTubeTranscriptService();
        fetchCaptionContent.mockResolvedValue(CAPTION_XML);
    });

    it('returns fullText, language, and the ASR flag on success', async () => {
        fetchPlayerResponse.mockResolvedValue(captionsResponse() as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(true);
        if (outcome.ok) {
            expect(outcome.transcript.fullText).toBe('age gated words');
            expect(outcome.transcript.language).toBe('en');
            expect(outcome.transcript.isAutoGenerated).toBe(true);
            expect(outcome.transcript.truncated).toBe(false);
            expect(outcome.transcript.segments[0]?.start).toBe(0.5);
        }
    });

    it('maps an age gate to restricted and recovers via the innertube fallback', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('LOGIN_REQUIRED', 'Sign in to confirm your age') as never);
        fetchInnertubePlayerResponse.mockResolvedValue(captionsResponse());

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(true);
        if (outcome.ok) expect(outcome.transcript.fullText).toBe('age gated words');
        expect(fetchInnertubePlayerResponse).toHaveBeenCalledTimes(1);
        expect(fetchInnertubePlayerResponse).toHaveBeenCalledWith(VIDEO_ID);
        // Second argument is the optional run signal.
        expect(fetchCaptionContent.mock.calls[0]?.[0]).toBe('https://caption/en');
    });

    it('returns the original restricted outcome when the innertube fallback fails', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('LOGIN_REQUIRED', 'Sign in to confirm your age') as never);
        fetchInnertubePlayerResponse.mockRejectedValue(new Error('boom'));

        const outcome: TranscriptOutcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome).toEqual({
            ok: false,
            reason: 'restricted',
            message: 'Sign in to confirm your age',
        });
    });

    it('keeps restricted when the fallback response has no caption tracks', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('LOGIN_REQUIRED', 'Sign in to confirm your age') as never);
        fetchInnertubePlayerResponse.mockResolvedValue({ playabilityStatus: { status: 'OK' } });

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('restricted');
        expect(fetchCaptionContent).not.toHaveBeenCalled();
    });

    it('maps a private video to private', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('LOGIN_REQUIRED', 'This video is private') as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) {
            expect(outcome.reason).toBe('private');
            expect(outcome.message).toContain('private');
        }
        expect(fetchInnertubePlayerResponse).not.toHaveBeenCalled();
    });

    it('maps an age-gated error screen to restricted even without a reason string', async () => {
        fetchPlayerResponse.mockResolvedValue(
            playability('LOGIN_REQUIRED', '', { playerAgeRestrictedRenderer: {} }) as never,
        );
        fetchInnertubePlayerResponse.mockResolvedValue(captionsResponse());

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);
        expect(outcome.ok).toBe(true);
    });

    it.each([
        ['removed video', playability('ERROR', 'Video unavailable')],
        ['404', playability('ERROR', 'Http 404')],
    ])('maps %s to unavailable', async (_name, playerResponse) => {
        fetchPlayerResponse.mockResolvedValue(playerResponse as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('unavailable');
    });

    it('maps a region block to restricted', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('UNPLAYABLE', 'This video is not available in your country'));

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('restricted');
    });

    it('maps a missing caption track list to no-captions', async () => {
        fetchPlayerResponse.mockResolvedValue({ playabilityStatus: { status: 'OK' } } as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('no-captions');
    });

    it('maps an unparseable page to unknown', async () => {
        fetchPlayerResponse.mockResolvedValue(null as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('unknown');
    });

    it('maps a thrown page fetch to network', async () => {
        fetchPlayerResponse.mockRejectedValue(new Error('socket hang up') as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome).toEqual({ ok: false, reason: 'network', message: 'socket hang up' });
    });

    it('maps a thrown caption download to network', async () => {
        fetchPlayerResponse.mockResolvedValue(captionsResponse() as never);
        fetchCaptionContent.mockRejectedValue(new Error('timed out') as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(false);
        if (!outcome.ok) expect(outcome.reason).toBe('network');
    });

    it('flags truncated once the character ceiling is reached', async () => {
        fetchPlayerResponse.mockResolvedValue(captionsResponse() as never);
        const chunk = 'a'.repeat(20_000);
        const xml = Array.from({ length: 10 }, (_, i) => `<text start="${i}" dur="1">${chunk}</text>`).join('');
        fetchCaptionContent.mockResolvedValue(`<transcript>${xml}</transcript>`);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(true);
        if (outcome.ok) {
            expect(outcome.transcript.truncated).toBe(true);
            expect(outcome.transcript.segments.length).toBeLessThan(10);
            expect(outcome.transcript.fullText.length).toBeLessThanOrEqual(150_000 + 20_000);
        }
    });

    it('keeps the legacy wrapper null-based', async () => {
        fetchPlayerResponse.mockResolvedValue(playability('LOGIN_REQUIRED', 'This video is private') as never);
        expect(await service.getTranscript(VIDEO_ID)).toBeNull();
    });
});

describe('TranscriptDiskCache', () => {
    const CACHE_DIR = '.obsidian/plugins/youtube-to-note/cache/transcripts';
    const CACHED = {
        savedAt: Date.now(),
        language: 'en',
        transcript: { fullText: 'cached', segments: [{ start: 0, duration: 1, text: 'cached' }], language: 'en' },
    };

    function fakeAdapter() {
        return {
            getBasePath: jest.fn(() => '/vault'),
            exists: jest.fn(async () => false),
            read: jest.fn(async () => JSON.stringify(CACHED)),
            write: jest.fn(async () => undefined),
            rename: jest.fn(async () => undefined),
            mkdir: jest.fn(async () => undefined),
            remove: jest.fn(async () => undefined),
            rmdir: jest.fn(async () => undefined),
            list: jest.fn(async () => ({ files: [], folders: [] })),
        };
    }

    function serviceWith(adapter: ReturnType<typeof fakeAdapter>, persist: boolean) {
        const app = { vault: { adapter } } as unknown as App;
        const diskCache = new TranscriptDiskCache(app);
        return {
            adapter,
            diskCache,
            service: new YouTubeTranscriptService(undefined, {
                diskCache,
                getSettings: () => ({ persistTranscriptCache: persist }) as never,
            }),
        };
    }

    beforeEach(() => {
        // reset (not clear) so mockResolvedValue set in one test cannot leak into the next.
        jest.resetAllMocks();
        fetchCaptionContent.mockResolvedValue(CAPTION_XML);
    });

    it('reads from disk before the network when enabled', async () => {
        const { adapter, service } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(true);
        if (outcome.ok) expect(outcome.transcript.fullText).toBe('cached');
        expect(fetchPlayerResponse).not.toHaveBeenCalled();
        expect(adapter.read).toHaveBeenCalledWith(expect.stringContaining(`/cache/transcripts/${VIDEO_ID}.auto.json`));
    });

    it('stores successful fetches through a temp file rename', async () => {
        const { adapter, service } = serviceWith(fakeAdapter(), true);
        fetchPlayerResponse.mockResolvedValue(captionsResponse() as never);

        await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(adapter.write).toHaveBeenCalledWith(expect.stringContaining('.tmp'), expect.any(String));
        expect(adapter.rename).toHaveBeenCalledWith(expect.stringContaining('.tmp'), expect.stringContaining('.json'));
    });

    it('never touches disk when the setting is off', async () => {
        const { adapter, service } = serviceWith(fakeAdapter(), false);
        fetchPlayerResponse.mockResolvedValue(captionsResponse() as never);

        const outcome = await service.fetchTranscriptOutcome(VIDEO_ID);

        expect(outcome.ok).toBe(true);
        expect(adapter.exists).not.toHaveBeenCalled();
        expect(adapter.write).not.toHaveBeenCalled();
    });

    it('ignores expired entries', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        adapter.read.mockResolvedValue(JSON.stringify({ ...CACHED, savedAt: Date.now() - 1000 * 60 * 60 * 24 * 8 }));

        expect(await diskCache.get(VIDEO_ID)).toBeNull();
        expect(adapter.remove).toHaveBeenCalled();
    });

    it('degrades to no-cache when a read fails', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockRejectedValue(new Error('disk offline'));

        expect(await diskCache.get(VIDEO_ID)).toBeNull();
    });

    it('swallows write failures', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.write.mockRejectedValue(new Error('read-only vault'));

        await expect(diskCache.set(VIDEO_ID, 'en', CACHED.transcript)).resolves.toBeUndefined();
    });

    it('refuses to build a path from a malformed video id', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);

        expect(await diskCache.get('../../etc/passd')).toBeNull();
        expect(adapter.exists).not.toHaveBeenCalled();
    });

    it('creates the directories the cache actually writes to', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(false);

        await diskCache.set(VIDEO_ID, 'en', CACHED.transcript);

        const created = adapter.mkdir.mock.calls.map(call => String(call[0]));
        // Every ancestor of the write path, in order — derived from the path the
        // cache writes to, so no stray "<vault>/youtube-to-note/cache" appears
        // at the vault root and the real parent is never left missing.
        expect(created).toEqual([
            '.obsidian',
            '.obsidian/plugins',
            '.obsidian/plugins/youtube-to-note',
            '.obsidian/plugins/youtube-to-note/cache',
            `${CACHE_DIR}`,
        ]);
    });

    it('treats malformed JSON as a miss and deletes the file', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        adapter.read.mockResolvedValue('{"savedAt":oops');

        expect(await diskCache.get(VIDEO_ID)).toBeNull();
        expect(adapter.remove).toHaveBeenCalledWith(expect.stringContaining(`${VIDEO_ID}.auto.json`));
    });

    it.each([
        ['missing savedAt', { language: 'en', transcript: CACHED.transcript }],
        ['non-numeric savedAt', { ...CACHED, savedAt: 'yesterday' }],
        ['non-finite savedAt', { ...CACHED, savedAt: Number.NaN }],
        ['missing fullText', { ...CACHED, transcript: { segments: [] } }],
        ['non-array segments', { ...CACHED, transcript: { fullText: 'x', segments: 'none' } }],
    ])('treats a cached entry with %s as a miss and deletes it', async (_label, payload) => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        adapter.read.mockResolvedValue(JSON.stringify(payload));

        expect(await diskCache.get(VIDEO_ID)).toBeNull();
        expect(adapter.remove).toHaveBeenCalledWith(expect.stringContaining(`${VIDEO_ID}.auto.json`));
    });

    it('sweeps leftover temp files on the first write', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        adapter.list.mockResolvedValue({
            files: [`${CACHE_DIR}/other.json`, `${CACHE_DIR}/other.json.tmp-k2-abc`, `${CACHE_DIR}/older.json.tmp`],
            folders: [],
        });

        await diskCache.set(VIDEO_ID, 'en', CACHED.transcript);

        expect(adapter.remove).toHaveBeenCalledWith(`${CACHE_DIR}/other.json.tmp-k2-abc`);
        expect(adapter.remove).toHaveBeenCalledWith(`${CACHE_DIR}/older.json.tmp`);
        expect(adapter.remove).not.toHaveBeenCalledWith(`${CACHE_DIR}/other.json`);
    });

    it('names its temp file uniquely so two concurrent writes cannot collide', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);

        await Promise.all([
            diskCache.set(VIDEO_ID, 'en', CACHED.transcript),
            diskCache.set(VIDEO_ID, 'fr', CACHED.transcript),
        ]);

        const temps = adapter.write.mock.calls.map(call => String(call[0]));
        expect(temps).toHaveLength(2);
        expect(new Set(temps).size).toBe(2);
        for (const temp of temps) expect(temp).toMatch(/\.tmp-[0-9a-z]+-[0-9a-z]+$/i);
    });

    it('prunes the oldest entries once the cache is full', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        const files = Array.from(
            { length: TRANSCRIPT_CACHE_MAX_FILES + 1 },
            (_, i) => `${CACHE_DIR}/aaaaaaaaaaa${i}.json`,
        );
        adapter.list.mockResolvedValue({ files, folders: [] });
        // savedAt rises with the index, so entry 0 is the one to drop.
        adapter.read.mockImplementation((path: string) =>
            Promise.resolve(
                JSON.stringify({
                    savedAt: 1000 + Number(path.match(/(\d+)\.json$/)?.[1] ?? 0),
                    transcript: CACHED.transcript,
                }),
            ),
        );

        await diskCache.set(VIDEO_ID, 'en', CACHED.transcript);

        expect(adapter.remove).toHaveBeenCalledTimes(1);
        expect(adapter.remove).toHaveBeenCalledWith(`${CACHE_DIR}/aaaaaaaaaaa0.json`);
    });

    it('leaves the cache alone while it is under the size cap', async () => {
        const { adapter, diskCache } = serviceWith(fakeAdapter(), true);
        adapter.exists.mockResolvedValue(true);
        adapter.list.mockResolvedValue({
            files: Array.from({ length: TRANSCRIPT_CACHE_MAX_FILES }, (_, i) => `${CACHE_DIR}/aaaaaaaaaaa${i}.json`),
            folders: [],
        });

        await diskCache.set(VIDEO_ID, 'en', CACHED.transcript);

        expect(adapter.remove).not.toHaveBeenCalledWith(expect.stringContaining(`${CACHE_DIR}/aaaaaaaaaaa`));
    });
});
